# Generated by Django 5.0.4 on 2024-08-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_level',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Avançado', 'Avançado'), ('Normal', 'Normal')], default='Normal', max_length=20),
        ),
    ]
