# Generated by Django 5.0.4 on 2024-08-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_level',
            field=models.CharField(choices=[('Master', 'Master'), ('Gerencial', 'Gerencial'), ('Administrador', 'Administrador'), ('Visualizador', 'Visualizador')], default='Visualizador', max_length=20),
        ),
    ]
