# Generated by Django 5.0.4 on 2024-08-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_profile_first_name_remove_profile_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('ir', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
