# Generated by Django 5.0.4 on 2024-08-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_matrizreceitas'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetasEscritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50)),
                ('meta_roa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('meta_nps', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
