# Generated by Django 5.0.4 on 2024-08-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_metasescritorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metasescritorio',
            name='meta_nps',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='metasescritorio',
            name='meta_roa',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='metasescritorio',
            name='periodo',
            field=models.CharField(max_length=7),
        ),
    ]
