# Generated by Django 5.0.4 on 2024-08-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_metasescritorio_meta_nps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metasescritorio',
            name='periodo',
            field=models.CharField(max_length=8),
        ),
    ]
