# Generated by Django 5.0.4 on 2024-09-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_metasescritorio_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metasescritorio',
            name='periodo',
            field=models.CharField(max_length=7),
        ),
    ]
