# Generated by Django 5.0.4 on 2024-09-03 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_metasescritorio_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='metasescritorio',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='metasescritorio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
