# Generated by Django 5.0.4 on 2024-09-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_matrizreceitas_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matrizreceitas',
            options={'managed': False},
        ),
    ]
