# Generated by Django 5.0.4 on 2024-09-12 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_matrizreceitas_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matrizreceitas',
            options={'managed': True},
        ),
    ]
