from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('api/market-data', views.market_data, name='market_data'),
    path('metas', views.metas, name='metas'),
    path('atualizar_meta/', views.atualizar_meta, name='atualizar_meta'),
    path('acd-liberta/', views.acd_liberta, name='acd_liberta'),
    path('alocacao-produtos/', views.alocacao_produtos, name='alocacao_produtos'),
    path('assessoria-comercial/', views.assessoria_comercial, name='assessoria_comercial'),
    path('atendimento-dgt/', views.atendimento_dgt, name='atendimento_dgt'),
    path('gerencial-assessoria/', views.gerencial_assessoria, name='gerencial_assessoria'),
    path('editar_repasse/', views.editar_repasse, name='editar_repasse'),
    path('excluir_repasse/', views.excluir_repasse, name='excluir_repasse'),
    path('cadastrar_repasse/', views.cadastrar_repasse, name='cadastrar_repasse'),
    path('cadastrar-escritorio/', views.cadastrar_escritorio, name='cadastrar_escritorio'),
    path('editar-escritorio/', views.editar_escritorio, name='editar_escritorio'),
    path('excluir-escritorio/', views.excluir_escritorio, name='excluir_escritorio'),
    path('metas-escritorio/', views.metas_escritorio_view, name='metas_escritorio_view'),
    path('editar-meta/', views.editar_meta, name='editar_meta'),
    path('excluir-meta/', views.excluir_meta, name='excluir_meta'),
    path('editar_receita/<str:data_referencia>/', views.editar_receita, name='editar_receita'),
    path('excluir-receita/<str:data_referencia>/', views.excluir_receita, name='excluir-receita'),
    path('adicionar_receita/', views.adicionar_receita, name='adicionar_receita'),
    path('gestao-pessoas/', views.gestao_pessoas, name='gestao_pessoas'),
    path('editar_senioridade/', views.update_senioridade, name='update_senioridade'),
    path('delete_senioridade/', views.delete_senioridade, name='delete_senioridade'),
    path('editar_squad/', views.update_squad, name='update_squad'),
    path('delete_squad/', views.delete_squad, name='delete_squad'),
    path('update_cargo/', views.update_cargo, name='update_cargo'),
    path('delete_cargo/', views.delete_cargo, name='delete_cargo'),
    path('info-user/', views.info_user, name='info_user'),
    path('lib-wealth/', views.lib_wealth, name='lib_wealth'),
    path('pj-cred-camb/', views.pj_cred_camb, name='pj_cred_camb'),
    path('rv/', views.rv, name='rv'),
    path('seguridade/', views.seguridade, name='seguridade'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('get_email_by_name/', views.get_email_by_name, name='get_email_by_name'),
    path('get_department_by_name/', views.get_department_by_name, name='get_department_by_name'),
    path('manage-users/', views.manage_users, name='manage_users'),
    path('log-igla/', views.log_view, name='log_view'),
    path('teste/', views.teste_view, name='teste_view'),
]